name: Continuous integration
on: [push]
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
services:
  postgres:
    image: postgres:latest
    env:
      POSTGRES_USER: ${{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    ports:
      - 5432:5432
jobs:
  ruby_dependencies:
    name: Ruby - download and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-
      - name: Install gems
        run: bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Create database
        run: |
          rails db:create RAILS_ENV=test
          rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: rspec
      - name: Check code
        run: rubocop